version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      HOSTNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes: 
      - ./data-psql:/var/lib/postgresql/data
    networks:
      - psql
      - common
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - psql
    restart: unless-stopped


  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      - mongo
      - common
    restart: unless-stopped
    volumes:
      - ./data-mongo:/data/db
      - ./config-mongo:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_started
    networks:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/

  apache:
    container_name: apache
    image: httpd:latest
    restart: unless-stopped
    networks:
      - common
    ports:
      - 8888:80
    volumes:
      - ./website:/usr/local/apache2/htdocs

networks:
  mongo: {}
  psql: {}
  common: {}