version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      HOSTNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes: 
      - data-psql:/var/lib/postgresql/data
    networks:
      - psql
      - common
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer:latest
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080
    networks:
      - psql
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - redis
      - common
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - data-redis:/data

  web:
    container_name: php-web
    image: custom-php-apache
    restart: unless-stopped
    networks:
      - common
    ports:
      - 8888:80
    volumes:
      - ./website:/var/www/html/

volumes: 
    data-psql:
    data-redis:

networks:
  redis: {}
  psql: {}
  common: {}