version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      HOSTNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
    networks:
      net: {}

  admirer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      net: {}

networks:
  net: {}