FROM php:8-apache
RUN apt-get update && apt-get upgrade -y && apt-get install -y vim git make libpq-dev
ADD "php.ini-production" "$PHP_INI_DIR/php.ini"
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions
RUN install-php-extensions pdo_pgsql pgsql
RUN pecl install redis && docker-php-ext-enable pdo_pgsql redis
# RUN pecl install pgsql && docker-php-ext-enable pgsql
# RUN pecl install redis && docker-php-ext-enable redis.so
RUN sed -i 's/;extension=pdo_pgsql/extension=pdo_pgsql/g' $PHP_INI_DIR/php.ini
RUN sed -i 's/;extension=pgsql/extension=pgsql/g' $PHP_INI_DIR/php.ini
RUN echo "extension=redis.so" >> $PHP_INI_DIR/php.ini